using Entidades;
using Servicios;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;


namespace ClinicaMedica
{
    public partial class ListadoTurnos : System.Web.UI.Page
    {
        bool estado = false;
        private GestionTablas gestionTablas = new GestionTablas();
        private GestionDdl gestionDdl = new GestionDdl();
        protected void Page_Load(object sender, EventArgs e)
        {
            ComprobacionDeSesion();
            HabilitacionDeAcceso();
            gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos();
            gvTurnos.DataBind();

            gestionDdl.CargarFechas(ddlFechas);
           
        }

        protected void btnLogin_Click(object sender, EventArgs e)
        {
            if (Session["UsuarioActivo"] == null)
            {
                string user = txtUsuario.Text;
                string pass = txtContrasenia.Text;

                GestionUsuario gestionUsuario = new GestionUsuario();

                Usuario usuario = gestionUsuario.Loguear(user, pass);

                if (usuario != null)
                {
                    Session["UsuarioActivo"] = usuario;
                    ComprobacionDeSesion();
                }
                else
                {
                    lblBienvenidoUsuario.ForeColor = System.Drawing.Color.Red;
                    lblBienvenidoUsuario.Text = "Usuario o contraseña incorrectos";
                }
            }
        }

        protected void ComprobacionDeSesion()
        {
            if (Session["UsuarioActivo"] != null)
            {
                btnLogin.Visible = false;
                btnUnlogin.Visible = true;
                txtContrasenia.Visible = false;
                txtUsuario.Visible = false;
                lblContrasenia.Visible = false;
                lblNombreUsuario.Visible = false;
                hlCambiarContrasenia.Visible = true;
                lblBienvenidoUsuario.ForeColor = System.Drawing.Color.White;
                lblBienvenidoUsuario.Text = ((Usuario)Session["UsuarioActivo"]).NombreUsuario + " " + ((Usuario)Session["UsuarioActivo"]).ApellidoUsuario;
                HabilitacionDeAcceso();
            }
            else
            {
                btnLogin.Visible = true;
                btnUnlogin.Visible = false;
                txtContrasenia.Visible = true;
                txtUsuario.Visible = true;
                lblContrasenia.Visible = true;
                lblNombreUsuario.Visible = true;
                lblBienvenidoUsuario.Text = string.Empty;
                HabilitacionDeAcceso();
            }
        }

        protected void btnUnlogin_Click(object sender, EventArgs e)
        {
            Session["UsuarioActivo"] = null;
            ComprobacionDeSesion();
        }


        protected void HabilitacionDeAcceso()
        {
            if (Session["UsuarioActivo"] != null)
            {
                if (((Usuario)Session["UsuarioActivo"]).TipoUsuario > 1)
                {
                    gvTurnos.AutoGenerateDeleteButton = true;
                    gvTurnos.AutoGenerateEditButton = true;

                    hlAgregarMedico.Visible = true;

                    hlAsignarTurnos.Visible = true;
                    hlInformes.Visible = true;
                    hlListarMedicos.Visible = true;
                }
                if (((Usuario)Session["UsuarioActivo"]).TipoUsuario >= 1)
                {
                    gvTurnos.AutoGenerateSelectButton = true;

                    hlListarTurnos.Visible = true;
                    hlSeguimientoPaciente.Visible = true;
                    btnFiltroFecha.Visible = true;
                    ddlFechas.Visible = true;
                    btnMostrarTodo.Visible = true;
                    btnConsultarEstado.Visible = true;
                    ddlEstados.Visible = true;
                }
            }
            else
            {
                gvTurnos.AutoGenerateDeleteButton = false;
                gvTurnos.AutoGenerateEditButton = false;
                gvTurnos.AutoGenerateSelectButton = false;
                hlAgregarMedico.Visible = false;

                hlAsignarTurnos.Visible = false;
                hlInformes.Visible = false;
                hlListarMedicos.Visible = false;
                hlListarTurnos.Visible = false;
                hlSeguimientoPaciente.Visible = false;
                btnFiltroFecha.Visible = false;
                ddlFechas.Visible = false;
                btnMostrarTodo.Visible = false;
                btnConsultarEstado.Visible = false;
                ddlEstados.Visible = false;
            }
        }

        protected void gvTurnos_PageIndexChanging(object sender, GridViewPageEventArgs e)
        {
            gvTurnos.PageIndex = e.NewPageIndex;
            gvTurnos.DataBind();
        }

        protected void gvTurnos_SelectedIndexChanged(object sender, EventArgs e)
        {
         
        }

        protected void gvTurnos_RowEditing(object sender, GridViewEditEventArgs e)
        {
            gvTurnos.EditIndex = e.NewEditIndex;
            gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos();
            gvTurnos.DataBind();
        }

        protected void gvTurnos_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            //Logico de eliminar va aqui o el llamado a eliminar el turno, se hace a traves del mismo metodo de asignar turno,
            //aunque hay que ver como exactamente, si no me equivoco creo que pasando los datos del turno sin el dni
            gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos();
            gvTurnos.DataBind();
        }

        protected void gvTurnos_RowUpdating(object sender, GridViewUpdateEventArgs e)
        {

        }

    }
}