using Entidades;
using Servicios;
using System;
using System.Data;
using System.Reflection.Emit;
using System.Web.UI.WebControls;


namespace ClinicaMedica
{
    public partial class ListadoTurnos : System.Web.UI.Page
    {
        //bool estado = false;
        private GestionTablas gestionTablas = new GestionTablas();
        private GestionDdl gestionDdl = new GestionDdl();
        Turno ConfiguracionTurno = new Turno();
        private GestionRegistros GestorRegistros = new GestionRegistros();

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                gestionDdl.CargarFechas(ddlFechas);
                gestionDdl.CargarEstados(ddlEstados);

                ComprobacionDeSesion();
                HabilitacionDeAcceso();
            }
        }

        protected void btnLogin_Click(object sender, EventArgs e)
        {
            if (Session["UsuarioActivo"] == null)
            {
                string user = txtUsuario.Text;
                string pass = txtContrasenia.Text;

                GestionUsuario gestionUsuario = new GestionUsuario();


                Usuario usuario = gestionUsuario.Loguear(user, pass);
                

                if (usuario != null)
                {
                    Session["UsuarioActivo"] = usuario;
                    ComprobacionDeSesion();
                }
                else
                {
                    lblBienvenidoUsuario.ForeColor = System.Drawing.Color.Red;
                    lblBienvenidoUsuario.Text = "Usuario o contraseña incorrectos";
                }
            }
        }

        protected void ComprobacionDeSesion()
        {
            if (Session["UsuarioActivo"] != null)
            {
                btnLogin.Visible = false;
                btnUnlogin.Visible = true;
                txtContrasenia.Visible = false;
                txtUsuario.Visible = false;
                lblContrasenia.Visible = false;
                lblNombreUsuario.Visible = false;
                hlCambiarContrasenia.Visible = true;
                lblBienvenidoUsuario.ForeColor = System.Drawing.Color.White;
                lblBienvenidoUsuario.Text = ((Usuario)Session["UsuarioActivo"]).NombreUsuario + " " + ((Usuario)Session["UsuarioActivo"]).ApellidoUsuario;
                HabilitacionDeAcceso();
            }
            else
            {
                btnLogin.Visible = true;
                btnUnlogin.Visible = false;
                txtContrasenia.Visible = true;
                txtUsuario.Visible = true;
                lblContrasenia.Visible = true;
                lblNombreUsuario.Visible = true;
                lblBienvenidoUsuario.Text = string.Empty;
                gvTurnos.DataSource = null;
                gvTurnos.DataBind();
                HabilitacionDeAcceso();
            }
        }

        protected void btnUnlogin_Click(object sender, EventArgs e)
        {
            Session["UsuarioActivo"] = null;
            ComprobacionDeSesion();
        }

        protected void HabilitacionDeAcceso()
        {
            if (Session["UsuarioActivo"] != null)
            {
                if (((Usuario)Session["UsuarioActivo"]).TipoUsuario > 1)
                {
                    gvTurnos.AutoGenerateDeleteButton = true;
                    gvTurnos.AutoGenerateEditButton = true;

                    hlAgregarMedico.Visible = true;

                    hlAsignarTurnos.Visible = true;
                    hlInformes.Visible = true;
                    hlListarMedicos.Visible = true;

                    if (ddlFechas.SelectedItem != null 
                        && ddlFechas.SelectedValue != "0" 
                        && !string.IsNullOrWhiteSpace(ddlFechas.SelectedItem.Text))
                    {
                        ConfiguracionTurno.Fecha = DateTime.Parse(ddlFechas.SelectedItem.Text);
                    }

                    gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos(ConfiguracionTurno);
                    gvTurnos.DataBind();
                }
                if (((Usuario)Session["UsuarioActivo"]).TipoUsuario >= 1)
                {
                    gvTurnos.AutoGenerateSelectButton = true;

                    hlListarTurnos.Visible = true;
                    hlSeguimientoPaciente.Visible = true;
                    lblFecha.Visible = true;
                    ddlFechas.Visible = true;
                    btnMostrarTodo.Visible = true;
                    btnConsultarEstado.Visible = true;
                    ddlEstados.Visible = true;

                    if (((Usuario)Session["UsuarioActivo"]).TipoUsuario == 1)
                    {
                        gestionDdl.CargarFechas(ddlFechas, null, ((Usuario)Session["UsuarioActivo"]).LegajoDoctor);
                    }

                    Turno ConfiguracionTurno = new Turno();

                    if (ddlFechas.SelectedItem != null 
                        && ddlFechas.SelectedValue != "0" 
                        && !string.IsNullOrWhiteSpace(ddlFechas.SelectedItem.Text))
                    {
                        ConfiguracionTurno.Fecha = DateTime.Parse(ddlFechas.SelectedItem.Text);
                    }

                    ConfiguracionTurno.LegajoMed = ((Usuario)Session["UsuarioActivo"]).LegajoDoctor;

                    gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos(ConfiguracionTurno);
                    gvTurnos.DataBind();
                }
            }
            else
            {
                gvTurnos.AutoGenerateDeleteButton = false;
                gvTurnos.AutoGenerateEditButton = false;
                gvTurnos.AutoGenerateSelectButton = false;
                hlAgregarMedico.Visible = false;

                hlAsignarTurnos.Visible = false;
                hlInformes.Visible = false;
                hlListarMedicos.Visible = false;
                hlListarTurnos.Visible = false;
                hlSeguimientoPaciente.Visible = false;
                lblFecha.Visible = false;
                ddlFechas.Visible = false;
                btnMostrarTodo.Visible = false;
                btnConsultarEstado.Visible = false;
                ddlEstados.Visible = false;
            }
        }

        protected void gvTurnos_PageIndexChanging(object sender, GridViewPageEventArgs e)
        {
            gvTurnos.PageIndex = e.NewPageIndex;
            // Recupera el filtro de la Session
            Turno filtro = Session["FiltroTurno"] as Turno ?? new Turno();
            gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos(filtro);
            gvTurnos.DataBind();
        }

        protected void gvTurnos_RowEditing(object sender, GridViewEditEventArgs e)
        {
            gvTurnos.EditIndex = e.NewEditIndex;            
            gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos(ConfiguracionTurno);
            gvTurnos.DataBind();
        }

        protected void gvTurnos_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            //Aqui se desglosa Numero de turno, y se pueden sacar varios datos desde ahi

            string NumeroTurno = gvTurnos.DataKeys[e.RowIndex].Value.ToString();
            string[] Division = NumeroTurno.Split('-');
            int semana = int.Parse(Division[0]);
            int idDia = int.Parse(Division[1]);
            int idEspecialidad = int.Parse(Division[2]);
            int legajo = int.Parse(Division[3]);


            GridViewRow fila = gvTurnos.Rows[e.RowIndex];
            //Logico de eliminar va aqui o el llamado a eliminar el turno, se hace a traves del mismo metodo de asignar turno,
            //pasando los datos del turno sin el dni(dni null)
            ConfiguracionTurno = new Turno(
             null,idEspecialidad, legajo, Convert.ToDateTime(((System.Web.UI.WebControls.Label)fila.FindControl("lbl_it_Fecha")).Text),
             TimeSpan.Parse(((System.Web.UI.WebControls.Label)fila.FindControl("lbl_it_Horario")).Text)
             );

            int Retorno = GestorRegistros.RegistrarTurno(ConfiguracionTurno);

            ConfiguracionTurno = new Turno();
            Session["FiltroTurno"] = ConfiguracionTurno; 

            gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos(ConfiguracionTurno);
            gvTurnos.DataBind();
        }

        protected void gvTurnos_RowUpdating(object sender, GridViewUpdateEventArgs e)
        {
            //No estoy completamente seguro de que mas se deberia poder subir o actualizar desde aqui, asi que por el momento solo esta el DNI,
            //aunque hay un txt para el nombre del paciente es temporal ya que depende del dni asi que no tiene mucho sentido
            string NumeroTurno = gvTurnos.DataKeys[e.RowIndex].Value.ToString();
            string[] Division = NumeroTurno.Split('-');
            int semana = int.Parse(Division[0]);
            int idDia = int.Parse(Division[1]);
            int idEspecialidad = int.Parse(Division[2]);
            int legajo = int.Parse(Division[3]);

            GridViewRow fila = gvTurnos.Rows[e.RowIndex];

            ConfiguracionTurno = new Turno(
                ((TextBox)fila.FindControl("txt_it_DniPaciente")).Text, idEspecialidad, legajo, Convert.ToDateTime(((System.Web.UI.WebControls.Label)fila.FindControl("lbl_it_Fecha")).Text), 
                TimeSpan.Parse(((System.Web.UI.WebControls.Label)fila.FindControl("lbl_it_Horario")).Text)
                );

            int Retorno = GestorRegistros.RegistrarTurno(ConfiguracionTurno);

            gvTurnos.EditIndex = -1;//Salir del Edit

            ConfiguracionTurno = new Turno(); 
            Session["FiltroTurno"] = ConfiguracionTurno;
            gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos(ConfiguracionTurno);
            gvTurnos.DataBind();




        }
        protected void btnBuscar_Click(object sender, EventArgs e)
        {
            Turno PorDni = new Turno();
            PorDni.DniPaciente = txtBuscador.Text.Trim();
            if (!string.IsNullOrEmpty(txtBuscador.Text))
            {
                lblMensaje.Text = string.Empty;
                DataTable tablaFiltrada = gestionTablas.ObtenerTablaTurnos(PorDni);
                gvTurnos.DataSource = tablaFiltrada;
                gvTurnos.DataBind();
            }
            else
            {
                lblMensaje.Text = "Ingrese DNI a buscar.";
                lblMensaje.ForeColor = System.Drawing.Color.Red;
                gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos(ConfiguracionTurno);
                gvTurnos.DataBind();
            }
        }

        protected void btnMostrarTodo_Click(object sender, EventArgs e)
        {
            // mostrar todos los turnos
            ConfiguracionTurno = new Turno(); // Resetea el filtro
            Session["FiltroTurno"] = ConfiguracionTurno; // Guarda el filtro vacío en Session
            gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos(ConfiguracionTurno);
            gvTurnos.DataBind();
            txtBuscador.Text = string.Empty;
            ddlFechas.SelectedIndex = 0;
        }

        protected void ddlFechas_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (ddlFechas.SelectedItem != null
                    && ddlFechas.SelectedValue != "0"
                    && !string.IsNullOrWhiteSpace(ddlFechas.SelectedItem.Text))
            {
                ConfiguracionTurno.Fecha = DateTime.Parse(ddlFechas.SelectedItem.Text);
            }
            else
            {
                ConfiguracionTurno.Fecha = null;
            }

            if (((Usuario)Session["UsuarioActivo"]).TipoUsuario >= 1)
            {
                ConfiguracionTurno.LegajoMed = ((Usuario)Session["UsuarioActivo"]).LegajoDoctor;
            }

            // Guarda el filtro en Session
            Session["FiltroTurno"] = ConfiguracionTurno;

            gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos(ConfiguracionTurno);
            gvTurnos.DataBind();
            txtBuscador.Text = string.Empty;
        }

        protected void ddlEstados_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        protected void gvTurnos_RowCancelingEdit(object sender, GridViewCancelEditEventArgs e)
        {
            gvTurnos.EditIndex = -1;//Salir del Edit
            gvTurnos.DataSource = gestionTablas.ObtenerTablaTurnos(ConfiguracionTurno);
            gvTurnos.DataBind();
        }
    }
}
